package handlers

import (
	"bytes"
	"encoding/json"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
)

// createMultipartPayload generates a simulated multipart form file payload and its boundary content-type.
func createMultipartPayload(t *testing.T, fieldName, fileName, contentType string, fileContent []byte) (*bytes.Buffer, string) {
	buf := new(bytes.Buffer)
	writer := multipart.NewWriter(buf)

	if fileName != "" {
		// Attempt to create form file explicitly with a specific content-type
		part, err := writer.CreateFormFile(fieldName, fileName)
		if err != nil {
			t.Fatalf("Failed to create form file: %v", err)
		}

		// If custom content-type provided, override the multipart default application/octet-stream
		if contentType != "" {
			buf.Reset()
			writer = multipart.NewWriter(buf)

			// Manually construct the header part with an explicit Content-Type to trick gin context bindings correctly
			// since CreateFormFile hardcodes it unless replaced manually through textproto bindings
			header := make(map[string][]string)
			header["Content-Disposition"] = []string{`form-data; name="` + fieldName + `"; filename="` + fileName + `"`}
			header["Content-Type"] = []string{contentType}

			part, err = writer.CreatePart(header)
			if err != nil {
				t.Fatalf("Failed to create custom part: %v", err)
			}
			_, err = io.Copy(part, bytes.NewReader(fileContent))
			writer.Close()
			return buf, writer.FormDataContentType()
		}

		_, err = io.Copy(part, bytes.NewReader(fileContent))
		if err != nil {
			t.Fatalf("Failed to write to form file: %v", err)
		}
	}

	err := writer.Close()
	if err != nil {
		t.Fatalf("Failed to close multipart writer: %v", err)
	}

	return buf, writer.FormDataContentType()
}

func TestUploadProfilePicture(t *testing.T) {
	// Setup cleanup hook for simulated files generated by this test suite
	defer func() {
		files, _ := filepath.Glob("uploads/profile_test_*.jpg")
		for _, f := range files {
			os.Remove(f)
		}
	}()

	tests := []struct {
		name           string
		authenticated  bool
		userID         uint
		fieldName      string
		fileName       string
		contentType    string
		fileContent    []byte
		expectedStatus int
		expectContains string
	}{
		{
			name:           "Valid JPEG Upload",
			authenticated:  true,
			userID:         1,
			fieldName:      "image",
			fileName:       "profile_test_1.jpg",
			contentType:    "image/jpeg",
			fileContent:    []byte("dummy image byte data here"),
			expectedStatus: http.StatusOK,
			expectContains: "/uploads/profile_",
		},
		{
			name:           "Valid PNG Upload",
			authenticated:  true,
			userID:         2,
			fieldName:      "image",
			fileName:       "profile_test_2.png",
			contentType:    "image/png",
			fileContent:    []byte("dummy png data"),
			expectedStatus: http.StatusOK,
			expectContains: "/uploads/profile_",
		},
		{
			name:           "Unauthorized",
			authenticated:  false,
			userID:         0,
			fieldName:      "image",
			fileName:       "profile_test_3.jpg",
			contentType:    "image/jpeg",
			fileContent:    []byte("dummy"),
			expectedStatus: http.StatusUnauthorized,
			expectContains: "User ID not found in context",
		},
		{
			name:           "Invalid Field Name",
			authenticated:  true,
			userID:         1,
			fieldName:      "wrong_field", // Expected is "image"
			fileName:       "profile_test_4.jpg",
			contentType:    "image/jpeg",
			fileContent:    []byte("dummy"),
			expectedStatus: http.StatusBadRequest,
			expectContains: "No file is received",
		},
		{
			name:           "Invalid File Type",
			authenticated:  true,
			userID:         1,
			fieldName:      "image",
			fileName:       "malicious.exe",
			contentType:    "application/x-msdownload",
			fileContent:    []byte("fake executable bytes"),
			expectedStatus: http.StatusBadRequest,
			expectContains: "Invalid file type",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			r := setupGinTestRouter(UploadProfilePicture, tt.userID, tt.authenticated)
			r.POST("/upload", UploadProfilePicture)

			bodyBuf, contentType := createMultipartPayload(t, tt.fieldName, tt.fileName, tt.contentType, tt.fileContent)

			req, _ := http.NewRequest(http.MethodPost, "/upload", bodyBuf)
			req.Header.Set("Content-Type", contentType)

			w := httptest.NewRecorder()
			r.ServeHTTP(w, req)

			if w.Code != tt.expectedStatus {
				t.Errorf("Expected status %d but got %d", tt.expectedStatus, w.Code)
			}

			// Validate response body payload elements
			var response map[string]interface{}
			_ = json.Unmarshal(w.Body.Bytes(), &response)

			responseStr := w.Body.String()

			// Quick string substr checking for generic errors or success urls
			importStrings := requireRegex(tt.expectContains)
			if importStrings != "" && bytes.Index(w.Body.Bytes(), []byte(tt.expectContains)) == -1 {
				t.Errorf("Expected response body to contain '%s', got '%s'", tt.expectContains, responseStr)
			}
		})
	}
}

// Helper to pass simple strings or literal matches to tests easily via Index bounds.
func requireRegex(str string) string { return str }
